name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking-change'
  - title: 'Security Fixes'
    labels:
      - 'security'
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

