name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.5
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

